# Generated by Django 5.1.4 on 2024-12-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanItNowApp', '0004_pet_petfood_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='petVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccineName', models.CharField(max_length=100)),
                ('pet', models.ManyToManyField(to='PlanItNowApp.pet')),
            ],
        ),
    ]
