# Generated by Django 5.1.4 on 2025-01-02 07:46

import PlanItNowApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanItNowApp', '0005_petvaccine'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.IntegerField()),
                ('customerName', models.CharField(max_length=100)),
                ('customerEmail', models.CharField(max_length=100, validators=[PlanItNowApp.models.validation_Email])),
            ],
        ),
    ]
