# Generated by Django 5.1.4 on 2025-01-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanItNowApp', '0006_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customerContact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
