# Generated by Django 5.1.4 on 2025-01-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanItNowApp', '0007_customer_customercontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='petProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=100)),
                ('proDesc', models.TextField()),
                ('proPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('prodImage', models.ImageField(upload_to='images/')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
