# Generated by Django 5.1.4 on 2025-01-10 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanItNowApp', '0008_petproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='petProdCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categroyName', models.CharField(max_length=100)),
                ('categroyDesc', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='petproduct',
            old_name='rating',
            new_name='prodRating',
        ),
        migrations.AddField(
            model_name='petproduct',
            name='prodCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PlanItNowApp.petprodcategory'),
        ),
    ]
