# Generated by Django 5.1.4 on 2025-01-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanItNowApp', '0012_remove_cart_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='petproduct',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
