# Generated by Django 5.1.4 on 2025-01-30 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanItNowApp', '0015_cart_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='custForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custfullName', models.CharField(max_length=30)),
                ('custemailId', models.EmailField(max_length=254)),
                ('custphoneNo', models.CharField(max_length=15)),
                ('custAddress', models.TextField()),
                ('custcity', models.CharField(max_length=100)),
                ('pinCode', models.IntegerField(max_length=20)),
                ('countryName', models.CharField(max_length=100)),
                ('additionalNotes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
